<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$customerId = '';
$visitorId  = '';
if($customerSession->isLoggedIn()){ 
   $customerId = $customerSession->getCustomerId(); // if customer logged in then, store the customer id 
}
else
{
    $visitorId = $this->getVisitorId(); // if customer not logged in then store the visitor id
}

?>

<div class="mainbox">
    <div class="menu">
        <div class="back"><i class="fa fa-chevron-left"></i> </div>
        <div class="name">Support</div>   
    </div>
    <ol class="chat">
    
    </ol>
    <input class="textarea" id="idmsgsend" type="text" placeholder="Your message here.."/>
    
    <input type="hidden" id="idcustomerid" value="<?php echo $customerId; ?>" />
    <input type="hidden" id="idvisitorid" value="<?php echo $visitorId; ?>" />
</div>

<style>
.mainbox {
    position:relative;
    float:right;
    width:25%;
    top:0px;
}
.bet_time {
    position:absolute;
    bottom:0;
    right:0;
    background-color: red;
}    


/* M E N U */

.menu {
    float:left;
    top: 0px;
    left: 0px;
    right: 0px;
    width: 100%;
    height: 50px;
    background: rgba(82,179,217,0.9);
    z-index: 100;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
}

.back {
    position: absolute;
    width: 90px;
    height: 50px;
    top: 0px;
    left: 0px;
    color: #fff;
    line-height: 50px;
    font-size: 30px;
    padding-left: 10px;
    cursor: pointer;
}
.back img {
    position: absolute;
    top: 5px;
    left: 30px;
    width: 40px;
    height: 40px;
    background-color: rgba(255,255,255,0.98);
    border-radius: 100%;
    -webkit-border-radius: 100%;
    -moz-border-radius: 100%;
    -ms-border-radius: 100%;
    margin-left: 15px;
    }
.back:active {
    background: rgba(255,255,255,0.2);
}
.name{
    top: 3px;
    left: 110px;
    font-family: 'Lato';
    font-size: 25px;
    font-weight: 300;
    color: rgba(255,255,255,0.98);
    cursor: default;
}
.last{
    position: absolute;
    top: 30px;
    left: 115px;
    font-family: 'Lato';
    font-size: 11px;
    font-weight: 400;
    color: rgba(255,255,255,0.6);
    cursor: default;
}

/* M E S S A G E S */

.chat {
    overflow: auto;
    height: 150px;   
    list-style: none;
    background: none;
    margin: 0;
    padding: 0 0 50px 0;
    margin-top: 60px;
    margin-bottom: 10px;
    width: 100%;
    background-color: whitesmoke;
}
.chat li {
    padding: 0.5rem;
    overflow: hidden;
    display: flex;
}
.chat .avatar {
    width: 40px;
    height: 40px;
    position: relative;
    display: block;
    z-index: 2;
    border-radius: 100%;
    -webkit-border-radius: 100%;
    -moz-border-radius: 100%;
    -ms-border-radius: 100%;
    background-color: rgba(255,255,255,0.9);
}
.chat .avatar img {
    width: 40px;
    height: 40px;
    border-radius: 100%;
    -webkit-border-radius: 100%;
    -moz-border-radius: 100%;
    -ms-border-radius: 100%;
    background-color: rgba(255,255,255,0.9);
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
}
.chat .day {
    position: relative;
    display: block;
    text-align: center;
    color: #c0c0c0;
    height: 20px;
    text-shadow: 7px 0px 0px #e5e5e5, 6px 0px 0px #e5e5e5, 5px 0px 0px #e5e5e5, 4px 0px 0px #e5e5e5, 3px 0px 0px #e5e5e5, 2px 0px 0px #e5e5e5, 1px 0px 0px #e5e5e5, 1px 0px 0px #e5e5e5, 0px 0px 0px #e5e5e5, -1px 0px 0px #e5e5e5, -2px 0px 0px #e5e5e5, -3px 0px 0px #e5e5e5, -4px 0px 0px #e5e5e5, -5px 0px 0px #e5e5e5, -6px 0px 0px #e5e5e5, -7px 0px 0px #e5e5e5;
    box-shadow: inset 20px 0px 0px #e5e5e5, inset -20px 0px 0px #e5e5e5, inset 0px -2px 0px #d7d7d7;
    line-height: 38px;
    margin-top: 5px;
    margin-bottom: 20px;
    cursor: default;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
}

.other .msg {
    order: 1;
    border-top-left-radius: 0px;
    box-shadow: -1px 2px 0px #D4D4D4;
}
.other:before {
    content: "";
    position: relative;
    top: 0px;
    right: 0px;
    left: 40px;
    width: 0px;
    height: 0px;
    border: 5px solid #fff;
    border-left-color: transparent;
    border-bottom-color: transparent;
}

.self {
    justify-content: flex-end;
    align-items: flex-end;
}
.self .msg {
    order: 1;
    border-bottom-right-radius: 0px;
    box-shadow: 1px 2px 0px #D4D4D4;
}
.self .avatar {
    order: 2;
}
.self .avatar:after {
    content: "";
    position: relative;
    display: inline-block;
    bottom: 19px;
    right: 0px;
    width: 0px;
    height: 0px;
    border: 5px solid #fff;
    border-right-color: transparent;
    border-top-color: transparent;
    box-shadow: 0px 2px 0px #D4D4D4;
}

.msg {
    background: white;
    min-width: 50px;
    padding: 10px;
    border-radius: 2px;
    box-shadow: 0px 2px 0px rgba(0, 0, 0, 0.07);
}
.msg p {
    font-size: 0.8rem;
    margin: 0 0 0.2rem 0;
    color: #777;
}
.msg img {
    position: relative;
    display: block;
    width: 450px;
    border-radius: 5px;
    box-shadow: 0px 0px 3px #eee;
    transition: all .4s cubic-bezier(0.565, -0.260, 0.255, 1.410);
    cursor: default;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
}
@media screen and (max-width: 800px) {
    .msg img {
    width: 300px;
}
}
@media screen and (max-width: 550px) {
    .msg img {
    width: 200px;
}
}

.msg time {
    font-size: 0.7rem;
    color: #ccc;
    margin-top: 3px;
    float: right;
    cursor: default;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
}
.msg time:before{
    content:"\f017";
    color: #ddd;
    font-family: FontAwesome;
    display: inline-block;
    margin-right: 4px;
}

input.textarea {
    position: relative;
    bottom: 0px;
    left: 0px;
    right: 0px;
    width: 100%;
    height: 50px;
    z-index: 99;
    background: #fafafa;
    border: none;
    outline: none;
    padding-left: 55px;
    padding-right: 55px;
    color: #666;
    font-weight: 400;
}

</style>

<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function(){
           scrollchatbottom = true;
           $('#idmsgsend').keypress(function(event){
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if(keycode == '13' && !event.shiftKey ){
                    $.ajax({
                       url: "<?php echo $this->getUrlPath('supportchat/supportchat/messages/'); ?>",
                       data: {message:$('#idmsgsend').val(),customerid:$('#idcustomerid').val(),visitorid:$('#idvisitorid').val()},
                       method:"GET",
                       success: function(response)
                       {

                       },
                       fail: function(response)
                       {

                       }
                    });
                    $('#idmsgsend').val('');
                }

            });
            messageurl = "<?php echo $this->getUrlPath('supportchat/supportchat/messagesse'); ?>";
            messageurl = messageurl+"customerid/"+document.getElementById('idcustomerid').value+"/visitorid/"+document.getElementById('idvisitorid').value;
            var source = new EventSource(messageurl);
            source.onmessage = function(event) {
            jsonresponse = JSON.parse(event.data);
            var allmessages = "";
            $.each(jsonresponse, function(key,value){
                if (value.admin_id == null)
                {
                    allmessages = allmessages+"<li class='other'><div class='msg'><p>"+value.message+"</p><time>18:07</time></div></li>";
                }
                else
                {
                    allmessages = allmessages+"<li class='self'><div class='msg'><p>"+value.message+"</p><time>18:07</time></div></li>";
                }
                
            });
            $('.chat').html(allmessages);
            
            if (scrollchatbottom == true)
            {
                $('.chat').scrollTop( $('.chat').height()+300 )
            }
            };
            
            var clickedOnScrollbar = function(mouseX){
            if( $('.chat').outerWidth() <= mouseX ){
              return true;
            }
          }

          $('.chat').mousedown(function(e){
              
            if( clickedOnScrollbar(e.clientX) ){
             
            }
          });
          
          $('.chat').on('scroll', function() {
            if($(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight) {
                scrollchatbottom =  true; 
            }
            else
            {
                scrollchatbottom = false;
            }
        });
        });
 });

    </script>